# core/reporter.py — HTML and optional PDF report generation.
# 
# Given a ResultParser (or a list of Findings), renders an executive-summary
# HTML report with a technical breakdown table. PDF conversion uses WeasyPrint
# if available (graceful skip otherwise).

from __future__ import annotations

import importlib
import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from core.parser import Finding, ResultParser

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# HTML template (inline Jinja2-style, rendered with str.format)
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Moriarty Report — {target}</title>
  <style>
    :root {{
      --c-bg: #0d1117; --c-surface: #161b22; --c-border: #30363d;
      --c-text: #e6edf3; --c-muted: #8b949e;
      --c-critical: #f85149; --c-high: #f0883e;
      --c-medium: #d29922; --c-low: #3fb950; --c-info: #58a6ff;
    }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ background: var(--c-bg); color: var(--c-text); font-family: 'Segoe UI', system-ui, sans-serif; padding: 2rem; }}
    h1 {{ font-size: 1.8rem; margin-bottom: 0.25rem; }}
    .meta {{ color: var(--c-muted); font-size: 0.85rem; margin-bottom: 2rem; }}
    .exec-summary {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 1rem; margin-bottom: 2rem; }}
    .badge {{ background: var(--c-surface); border: 1px solid var(--c-border); border-radius: 8px;
              padding: 1rem; text-align: center; }}
    .badge .count {{ font-size: 2rem; font-weight: 700; }}
    .badge .label {{ font-size: 0.75rem; color: var(--c-muted); text-transform: uppercase; letter-spacing: 1px; }}
    .critical .count {{ color: var(--c-critical); }}
    .high .count {{ color: var(--c-high); }}
    .medium .count {{ color: var(--c-medium); }}
    .low .count {{ color: var(--c-low); }}
    .info .count {{ color: var(--c-info); }}
    table {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; }}
    th {{ background: var(--c-surface); border-bottom: 1px solid var(--c-border);
          padding: 0.75rem 1rem; text-align: left; color: var(--c-muted);
          text-transform: uppercase; letter-spacing: 0.5px; font-size: 0.75rem; }}
    td {{ padding: 0.65rem 1rem; border-bottom: 1px solid var(--c-border); vertical-align: top; }}
    tr:hover td {{ background: var(--c-surface); }}
    .sev {{ font-weight: 700; border-radius: 4px; padding: 2px 8px; font-size: 0.75rem; }}
    .sev-critical {{ background: #f8514920; color: var(--c-critical); }}
    .sev-high {{ background: #f0883e20; color: var(--c-high); }}
    .sev-medium {{ background: #d2992220; color: var(--c-medium); }}
    .sev-low {{ background: #3fb95020; color: var(--c-low); }}
    .sev-info {{ background: #58a6ff20; color: var(--c-info); }}
    code {{ background: var(--c-surface); border: 1px solid var(--c-border);
            border-radius: 4px; padding: 2px 6px; font-size: 0.8rem;
            display: block; overflow-x: auto; white-space: pre-wrap; word-break: break-all; }}
    h2 {{ margin: 1.5rem 0 1rem; font-size: 1.1rem; color: var(--c-muted);
          text-transform: uppercase; letter-spacing: 1px; font-size: 0.8rem; }}
    footer {{ margin-top: 3rem; color: var(--c-muted); font-size: 0.75rem; text-align: center; }}
  </style>
</head>
<body>
  <h1>🔍 Moriarty Security Report</h1>
  <p class="meta">Target: <strong>{target}</strong> &nbsp;|&nbsp; Generated: {generated_at} &nbsp;|&nbsp; Job: {job_id}</p>

  <h2>Executive Summary</h2>
  <div class="exec-summary">
    <div class="badge critical"><div class="count">{cnt_critical}</div><div class="label">Critical</div></div>
    <div class="badge high"><div class="count">{cnt_high}</div><div class="label">High</div></div>
    <div class="badge medium"><div class="count">{cnt_medium}</div><div class="label">Medium</div></div>
    <div class="badge low"><div class="count">{cnt_low}</div><div class="label">Low</div></div>
    <div class="badge info"><div class="count">{cnt_info}</div><div class="label">Info</div></div>
  </div>

  <h2>Technical Breakdown</h2>
  <table>
    <thead>
      <tr>
        <th>Severity</th>
        <th>Name</th>
        <th>URL</th>
        <th>Matched At</th>
        <th>Template</th>
        <th>Evidence (cURL)</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>
  <footer>Generated by Moriarty v1.0 — for authorised testing only.</footer>
</body>
</html>
"""

_ROW_TEMPLATE = """\
<tr>
  <td><span class="sev sev-{sev}">{sev_upper}</span></td>
  <td>{name}</td>
  <td><a href="{url}" style="color:inherit">{url}</a></td>
  <td>{matched_at}</td>
  <td>{template_id}</td>
  <td><code>{curl_cmd}</code></td>
</tr>"""


def _html_escape(s: str) -> str:
    return (s
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


# ---------------------------------------------------------------------------
# Reporter class
# ---------------------------------------------------------------------------

class Reporter:
    # Converts a list of Finding objects into HTML (and optionally PDF) reports.
    # 
    # Usage::
    # 
    #     reporter = Reporter(target="https://example.com", job_id="abc123")
    #     reporter.load_from_parser(parser)
    #     html_path = reporter.export_html(Path("reports/"))
    #     pdf_path  = reporter.export_pdf(Path("reports/"))  # no-op if weasyprint missing


    def __init__(self, target: str, job_id: str = "unknown") -> None:
        self.target = target
        self.job_id = job_id
        self._findings: list[Finding] = []

    def load_from_parser(self, parser: "ResultParser") -> None:
        self._findings = parser.sorted_findings()

    def load_from_list(self, findings: list["Finding"]) -> None:
        from core.parser import Severity, _SEVERITY_RANK
        self._findings = sorted(findings, key=lambda f: _SEVERITY_RANK.get(f.severity, 99))

    # ------------------------------------------------------------------

    def export_html(self, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        html = self._render_html()
        path = output_dir / f"moriarty_{self.job_id}.html"
        self._atomic_write(path, html)
        logger.info("[Reporter] HTML report → %s", path)
        return path

    def export_pdf(self, output_dir: Path) -> Path | None:
        # Convert the HTML report to PDF using WeasyPrint. Skip gracefully if not installed.

        weasyprint = _try_import("weasyprint")
        if weasyprint is None:
            logger.warning("[Reporter] WeasyPrint not installed — skipping PDF export.")
            return None

        html_path = self.export_html(output_dir)
        pdf_path = html_path.with_suffix(".pdf")
        try:
            weasyprint.HTML(filename=str(html_path)).write_pdf(str(pdf_path))
            logger.info("[Reporter] PDF report → %s", pdf_path)
            return pdf_path
        except Exception as exc:
            logger.error("[Reporter] PDF generation failed: %s", exc)
            return None

    # ------------------------------------------------------------------

    def _render_html(self) -> str:
        from core.parser import Severity
        stats = {s.value: 0 for s in Severity}
        for f in self._findings:
            stats[f.severity.value] = stats.get(f.severity.value, 0) + 1

        rows = "\n".join(
            _ROW_TEMPLATE.format(
                sev=f.severity.value,
                sev_upper=f.severity.value.upper(),
                name=_html_escape(f.name),
                url=_html_escape(f.url),
                matched_at=_html_escape(f.matched_at),
                template_id=_html_escape(f.template_id),
                curl_cmd=_html_escape(f.curl_cmd),
            )
            for f in self._findings
        )

        return _HTML_TEMPLATE.format(
            target=_html_escape(self.target),
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            job_id=self.job_id,
            cnt_critical=stats.get("critical", 0),
            cnt_high=stats.get("high", 0),
            cnt_medium=stats.get("medium", 0),
            cnt_low=stats.get("low", 0),
            cnt_info=stats.get("info", 0),
            rows=rows or "<tr><td colspan='6' style='text-align:center;color:#8b949e'>No findings.</td></tr>",
        )

    @staticmethod
    def _atomic_write(path: Path, content: str) -> None:
        tmp = path.with_suffix(path.suffix + ".tmp")
        try:
            tmp.write_text(content, encoding="utf-8")
            tmp.replace(path)
        except Exception:
            tmp.unlink(missing_ok=True)
            raise


def _try_import(name: str):
    try:
        return importlib.import_module(name)
    except ImportError:
        return None
