from __future__ import annotations

import re
from typing import NamedTuple


class _WafSig(NamedTuple):
    name: str
    # (header_name, pattern) checked case-insensitively on the header VALUE
    header_patterns: list[tuple[str, str]]
    # regex patterns matched against the response body (first 8 KB)
    body_patterns: list[str]


_SIGNATURES: list[_WafSig] = [
    _WafSig(
        name="Cloudflare",
        header_patterns=[
            ("cf-ray", r".+"),
            ("server", r"cloudflare"),
            ("cf-cache-status", r".+"),
        ],
        body_patterns=[
            r"Attention Required! \| Cloudflare",
            r"<title>Access denied \| .* used Cloudflare",
            r"ray ID [a-f0-9]{16}",
        ],
    ),
    _WafSig(
        name="Akamai",
        header_patterns=[
            ("x-check-cacheable", r".+"),
            ("x-akamai-transformed", r".+"),
            ("x-akamai-request-id", r".+"),
            ("server", r"akamaighost"),
        ],
        body_patterns=[
            r"<title>Access Denied</title>.*Akamai",
            r"Reference #\d+\.\w+\.",
        ],
    ),
    _WafSig(
        name="AWS WAF",
        header_patterns=[
            ("x-amzn-requestid", r".+"),
            ("x-amz-cf-id", r".+"),
        ],
        body_patterns=[
            r"<title>403 Forbidden</title>",
            r"Request blocked",
        ],
    ),
    _WafSig(
        name="Imperva / Incapsula",
        header_patterns=[
            ("x-iinfo", r".+"),
            ("x-cdn", r"incapsula"),
            ("set-cookie", r"incap_ses"),
        ],
        body_patterns=[
            r"Incapsula incident ID",
            r"_incap_ses",
            r"visid_incap",
        ],
    ),
    _WafSig(
        name="Sucuri",
        header_patterns=[
            ("x-sucuri-id", r".+"),
            ("x-sucuri-cache", r".+"),
            ("server", r"sucuri/cloudproxy"),
        ],
        body_patterns=[
            r"<title>Access Denied - Sucuri Website Firewall</title>",
            r"sucuri\.net/cloudproxy",
        ],
    ),
    _WafSig(
        name="ModSecurity",
        header_patterns=[
            ("server", r"mod_security"),
            ("x-mod-security", r".+"),
        ],
        body_patterns=[
            r"<title>406 Not Acceptable</title>",
            r"ModSecurity",
            r"This error was generated by Mod_Security",
        ],
    ),
    _WafSig(
        name="Barracuda",
        header_patterns=[
            ("server", r"barracuda"),
            ("x-barracuda-lc-enc", r".+"),
        ],
        body_patterns=[
            r"<title>Barracuda Web Application Firewall</title>",
            r"barra_counter_session",
        ],
    ),
    _WafSig(
        name="F5 BIG-IP ASM",
        header_patterns=[
            ("x-waf-event-info", r".+"),
            ("set-cookie", r"TS[0-9a-f]{8}="),
        ],
        body_patterns=[
            r"<title>Request Rejected</title>",
            r"The requested URL was rejected\. Please consult with your administrator",
        ],
    ),
    _WafSig(
        name="Wordfence",
        header_patterns=[],
        body_patterns=[
            r"Generated by Wordfence",
            r"<title>This site has been blocked",
            r"wordfence\.com",
        ],
    ),
]

_COMPILED: list[tuple[str, list[re.Pattern[str]]]] = [
    (sig.name, [re.compile(p, re.IGNORECASE | re.DOTALL) for p in sig.body_patterns])
    for sig in _SIGNATURES
]
_HEADER_COMPILED: list[tuple[str, list[tuple[str, re.Pattern[str]]]]] = [
    (
        sig.name,
        [(h, re.compile(p, re.IGNORECASE)) for h, p in sig.header_patterns],
    )
    for sig in _SIGNATURES
]


class WAFFingerprinter:
    def detect(
        self,
        headers: dict[str, str],
        body: str = "",
        status_code: int = 0,
    ) -> str | None:
        # Return the name of the detected WAF, or None.

        # Normalise headers to lowercase keys
        norm_headers = {k.lower(): v for k, v in headers.items()}
        body_snippet = body[:8192]

        scores: dict[str, int] = {}

        # header matching
        for name, patterns in _HEADER_COMPILED:
            for header_name, pattern in patterns:
                val = norm_headers.get(header_name, "")
                if val and pattern.search(val):
                    scores[name] = scores.get(name, 0) + 2

        # body pattern matching
        for name, patterns in _COMPILED:
            for pattern in patterns:
                if pattern.search(body_snippet):
                    scores[name] = scores.get(name, 0) + 3

        # 403/406 with short body is suspicious
        if status_code in (403, 406) and len(body_snippet) < 2000:
            # Bump all scores slightly
            for k in scores:
                scores[k] += 1

        if not scores:
            return None

        # Return WAF with highest score (minimum threshold: 2)
        best = max(scores, key=lambda k: scores[k])
        if scores[best] >= 2:
            return best
        return None

    def detect_from_fuzz_result(
        self,
        fuzz_result: dict,
        response_headers: dict[str, str] | None = None,
        response_body: str = "",
    ) -> str | None:
        # detect WAF from a fuzz_result JSON dict.

        status = fuzz_result.get("status", 0)
        return self.detect(
            headers=response_headers or {},
            body=response_body,
            status_code=status,
        )
